// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/drawabox/gallery/[gallery].tsx";
import * as $4 from "./routes/drawabox/index.tsx";
import * as $5 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/drawabox/gallery/[gallery].tsx": $3,
    "./routes/drawabox/index.tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
